### ISSUE TITLE
Shell scripts copied into bundle

### ISSUE THREAD

**Issue by tbrannam** [krzysztofzablocki/KZBootstrap#18]
It appears that when using Cocoapod of KZBootstrap that the KZ shell scripts are copied to Application Bundle

**Comment by Legoless** [comment]
Yes and this breaks the App Store deploy, because the code signature is not correct then. I'm looking into the issue, although this is recent, because I deployed many apps with KZBootstrap.

**Comment by skeeet** [comment]
So this issue appeared on April 21st. Apple rolled out new updates and updated iTunes backend.
Should be easy ti fix with something like

**Comment by linkrjr** [comment]
Has this change been force pushed into master?
I have the latest version(0.5.3) installed and this is not there.
I am having this invalid signature issue.

**Comment by Legoless** [comment]
@skeeet Did you check if this works? If so, create a pull request please.

**Comment by skeeet** [comment]
@Legoless i guess it is already merged.

**Comment by Legoless** [comment]
Yeah, you are correct about the merge, but @krzysztofzablocki needs to update the version and push the new pod, if we want to use it with CocoaPods without specifying Git repo.

**Comment by krzysztofzablocki** [comment]
sorry I've been swamped for last couple of months, try now on 0.5.4
