### ISSUE TITLE
Are you thinking about Swift support?

### ISSUE THREAD

**Issue by SpacyRicochet** [krzysztofzablocki/KZBootstrap#22]
Came across this project thanks to your work on the IconOverlay. This seems like a great utility! I'll definitely be using a lot of ideas for our next project.

Are you considering updating this for Swift projects as well?

**Comment by krzysztofzablocki** [comment]
open to PR's but until I start using swift in production I don't have time to do it myself

**Comment by SpacyRicochet** [comment]
Will have to look into it more closely… after creating a proper CI environment. But creating a proper bootstrap for Swift project is high on my list of priorities :)
