### ISSUE TITLE
Allow selection of bootstrap items

### ISSUE THREAD

**Issue by alanshutko** [krzysztofzablocki/KZBootstrap#29]
It would be nice to be able to pick and choose whether individual bootstrap items are on or off, by passing command line options to bootstrap.sh.

**Comment by alanshutko** [comment]
I will work on this and submit a pull request.

**Comment by alanshutko** [comment]
I've just finished a patch to do this. Is this a feature you prefer not to support?

**Comment by krzysztofzablocki** [comment]
I merged your PR, it looked like it already had that?

**Comment by alanshutko** [comment]
You did! I misunderstood how Github did pull requests (since I added that after the original pull).

Awesome, and thanks for a great bit of work.

**Comment by krzysztofzablocki** [comment]
thanks for PR, appreciated!
