### ISSUE TITLE
Swift 2.0 compatibility

### ISSUE THREAD

**Issue by lumenlunae** [krzysztofzablocki/KZBootstrap#30]
Hello! I have a swift 2.0 branch that updates processEnvironment.
https://github.com/lumenlunae/KZBootstrap

If you want to create a branch for swift 2.0, I can make a pull request. Thanks for this project!

**Comment by alanshutko** [comment]
I've noted the same issue. For me, I just changed things to Swift 2 without a branch.  My changes were otherwise exactly the same as lumenlunae, so I'd suggest taking that version.

**Comment by xilin** [comment]
Hi, @krzysztofzablocki , could you release a new version on CocoaPods for this issue?

**Comment by krzysztofzablocki** [comment]
@xilin it's live

**Comment by xilin** [comment]
Thanks for the quick response!
