### ISSUE TITLE
Extract icon versioning

### ISSUE THREAD

**Issue by revolter** [krzysztofzablocki/KZBootstrap#33]
I'm referring to the first screenshot from the `README` which adds information to the app's icon.

Upon running the example project, the app has no icon, hence no git information:

![ios simulator screen shot 9 sep 2015 15 43 16](https://cloud.githubusercontent.com/assets/5748627/9762072/9abeb78e-5709-11e5-8ea4-5838057bf599.jpg)

Also, is it possible to extract only this feature and use it in an existing _big_ project? I tried doing so to no avail. I don't know what the `bootstrap.sh` is doing at all; how can I debug it?

**Comment by revolter** [comment]
@krzysztofzablocki, @Legoless Any idea how to extract the brilliant icon versioning feature?

**Comment by revolter** [comment]
@krzysztofzablocki Is there any possibility to extract and use only the app icon versioning?

**Comment by krzysztofzablocki** [comment]
It's parametrized so you could, also you could just copy the script or check out my original icon versioning although I think bootstrap version is better

**Comment by revolter** [comment]
Could you provide some steps to achieve this? I tried it myself by looking at the provided example project but even that doesn't work, as stated in the original comment. Do I only need the shell script?

**Comment by krzysztofzablocki** [comment]
did you see original icon versioning I wrote, I did it years ago before bootstrap, you can try that as it's simple https://github.com/krzysztofzablocki/IconOverlaying

**Comment by revolter** [comment]
The [example](https://github.com/krzysztofzablocki/KZBootstrap/tree/master/Example) still doesn't work. Cloned this repo, ran `pod install`, ran the app, no icon. At least the example should work :(

**Comment by krzysztofzablocki** [comment]
it didn't work because the amount of required icons changes, I pushed updated set of icons and it's fine now
![screen shot 2016-08-17 at 13 06 59](https://cloud.githubusercontent.com/assets/1468993/17734277/82888836-647b-11e6-91db-8f38c0634fb6.png)

**Comment by revolter** [comment]
Working great, thanks!
