### ISSUE TITLE
Using iconVersioning.sh standalone

### ISSUE THREAD

**Issue by schjonhaug** [krzysztofzablocki/KZBootstrap#36]
I'm trying to use the iconVersioning script standalone in my project. It works, but I need to delete the derived data folder for the icon to update after it has been changed by the script the first time. However, when I look inside the derived data folder, the icons are correctly updated there.

Any ideas how I can make the script work standalone? Are there any thing from the other scripts that needs to be included?

**Comment by krzysztofzablocki** [comment]
springboard caches icons, so it might deploy correct one for you but not show it until you e.g. drag it into a folder

**Comment by schjonhaug** [comment]
Tried that, but with no luck. Still shows the old one.

**Comment by krzysztofzablocki** [comment]
did you try using https://github.com/krzysztofzablocki/IconOverlaying ? Although bootstrap has never version

**Comment by schjonhaug** [comment]
Yes, same result.

**Comment by krzysztofzablocki** [comment]
There were few changes since this was reported, we fixed couple of bugs so it should work now, works in the example project.
