### ISSUE TITLE
 unwrapping an Optional value 

### ISSUE THREAD

**Issue by Daopr** [krzysztofzablocki/KZBootstrap#40]
Hi, this error has confused me for along time

fatal error: unexpectedly found nil while unwrapping an Optional value
0  swift                    0x0000000109dc3fbb llvm::sys::PrintStackTrace(__sFILE*) + 43
1  swift                    0x0000000109dc46fb SignalHandler(int) + 379
2  libsystem_platform.dylib 0x00007fff8f3e4eaa _sigtramp + 26
3  libsystem_platform.dylib 0x00007fff6f181568 _sigtramp + 3755591384
4  libsystem_platform.dylib 0x000000010c579a23 _sigtramp + 2098809747
5  libsystem_platform.dylib 0x000000010c57660f _sigtramp + 2098796415
6  swift                    0x00000001083329bf llvm::MCJIT::runFunction(llvm::Function*, std::__1::vector<llvm::GenericValue, std::__1::allocator<llvm::GenericValue> > const&) + 271
7  swift                    0x00000001083350f6 llvm::ExecutionEngine::runFunctionAsMain(llvm::Function*, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, char const* const*) + 1190
8  swift                    0x00000001081c6d8c swift::RunImmediately(swift::CompilerInstance&, std::__1::vector<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >, std::__1::allocator<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> > > > const&, swift::IRGenOptions&, swift::SILOptions const&) + 2188
9  swift                    0x0000000107eb5151 performCompile(swift::CompilerInstance&, swift::CompilerInvocation&, llvm::ArrayRef<char const*>, int&) + 13425
10 swift                    0x0000000107eb1ad3 frontend_main(llvm::ArrayRef<char const*>, char const*, void*) + 2691
11 swift                    0x0000000107eae154 main + 2324
12 libdyld.dylib            0x00007fff9432c5ad start + 1
13 libdyld.dylib            0x000000000000000f start + 1808611939
Stack dump:
0.	Program arguments: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift -frontend -interpret /Volumes/OXT/Project/Hime/Pods/KZBootstrap/Pod/Assets/Scripts/processEnvironments.swift -target x86_64-apple-darwin15.3.0 -enable-objc-interop -sdk /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.11.sdk -module-name processEnvironments --    
/Volumes/OXT/Project/Hime/Pods/KZBootstrap/Pod/Assets/Scripts/bootstrap.sh: line 74: 13157 Illegal instruction: 4  env -i xcrun -sdk macosx swift "${DIR}/processEnvironments.swift" "${bundled_plist}" "${src_plist}" "${bundled_settings}"

**Comment by stevenoglesby** [comment]
I think you are missing a couple of the steps described in the 'Installing KZBootstrap' section of the readme.

So you need to create a KZBEnvironments.plist something like:

`<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>KZBEnvironments</key>
	<array>
		<string>QA</string>
		<string>STAGING</string>
		<string>PRODUCTION</string>
	</array>
</dict>
</plist>`

Then you also need to create a Setting.bundle file.

This should get you past the error.

**Comment by ForrestAlfred** [comment]
@stevenoglesby thanks for your help^!
